set shell := ["powershell.exe", "-Command"]
flash:
    cargo build --release
    rust-objcopy -O binary target/thumbv6m-none-eabi/release/adsr-envelope adsr-envelope-binary.bin
    stm32flash -w adsr-envelope-binary.bin -v COM5